---
driver:
  name: vagrant
  ssh:
    insert_key: false
  customize:
    cpus: 1
    memory: 2048

provisioner:
  name: chef_zero
  chef_client_path: /usr/bin/chef-client
  require_chef_omnibus: 12.14.89

transport:
  name: sftp

verifier:
  name: inspec
  format: doc

platforms:
  - name: debian-8.7
    run_list:
      - recipe[apt]
      - recipe[chef-apt-docker]

  - name: ubuntu-16.04
    run_list:
      - recipe[apt]
      - recipe[chef-apt-docker]

suites:
  - name: harbor
    run_list:
      - recipe[harbor]
    attributes:

